# ================================================================= #
#                ZoLiryzik Plugin Configuration                     #
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = #
#   Этот файл содержит все настраиваемые параметры для              #
#   плагина ZoLiryzik. Пожалуйста, внимательно читайте комментарии. #
# ================================================================= #

# Идентификатор Discord сервера (Guild ID), к которому будет подключаться бот.
# Это ОБЯЗАТЕЛЬНО должен быть ID вашего Discord сервера.
# Получается в Discord в режиме разработчика (правой кнопкой мыши по серверу -> Копировать ID).
main-discord-guild-id: "0000000000000000000000"

# Токен Discord бота. Получается на Discord Developer Portal.
# Держите его в секрете и НИКОГДА не делитесь им публично.
discord-bot-token: "BOT_TOKEN"

# Список Discord Role ID, которые имеют право использовать команду /zevent и !embed.
# Получается в Discord в режиме разработчика (правой кнопкой мыши по роли -> Копировать ID).
embed-creator-role-ids:
  - "0000000000000000000" # ID роли "Admin"
  - "0000000000000000000" # ID роли "Moderator"

# Цвет для Discord Embed-сообщений.
# Можно использовать HEX-коды (например, #FF0000 для красного)
# или шестнадцатеричные значения с префиксом 0x (например, 0xFF0000 для красного).
embed-color: "0xFFAA00"

# --- Сообщения для Minecraft игроков ---
messages:
  # Общие сообщения
  no-permission: "&cУ вас нет прав для использования этой команды."
  invalid-arguments: "&cНеверное использование команды. Используйте: &e/zevent &b\"title\" \"command\" \"duration\" \"channel_id\""
  command-executed: "Команда успешно выполнена!"
  command-failed: "&cКоманда не была выполнена из-за недостатка голосов."

  # Сообщения для команды /zevent
  vote-started: "&aГолосование начато в канале Discord &#FFD700%channel%&a!" # Gold color for channel name

  # Сообщения для команды /zlink (привязка аккаунтов)
  no-permission-zlink: "&cУ вас нет прав для использования этой команды."
  not-linked: "&cВаш аккаунт Minecraft не привязан к Discord."
  already-linked: "&aВаш аккаунт Minecraft уже привязан к Discord ID: &b%discord_tag%&a."
  link-start: "&aДля привязки аккаунта введите команду &b/link &e%code%&a в приватном сообщении Discord боту."
  link-timeout: "&7Этот код действует в течение 5 минут."
  linking-already-started: "&eУ вас уже есть активная сессия привязки. Используйте код: &b%code%&e в Discord."
  link-code-expired: "&cВаш код привязки истек."
  invalid-zlink-usage: "&cНеверное использование. Используйте &e/zlink &cдля проверки статуса или начала привязки."
  link-success-mc: "&aВаш аккаунт Minecraft успешно привязан к Discord: &b%discord_tag%&a!"
  unlink-success-mc: "&aВаш аккаунт Minecraft успешно отвязан от Discord."

  # Сообщения для команды /zunlink (отвязка аккаунтов)
  unlink-success-discord: "Ваш Discord аккаунт был отвязан от аккаунта Minecraft."

  # Сообщения, связанные со статусом голосового канала (используются в плейсхолдерах)
  in-voice-channel: "&aВы находитесь в голосовом канале Discord."
  not-in-voice-channel: "&cВы не находитесь в голосовом канале Discord."

# --- Сообщения для PlaceholderAPI ---
# Плейсхолдер, %zoliryzik_in_vc%.
placeholder-messages:
  not-linked: "&7Не привязан"
  guild-not-found: "&cОшибка сервера"
  in-vc: "&aВ голосовом канале"
  not-in-vc: "&cНе в голосовом канале"
  error: "&4Ошибка"